config/routes.rb
UReview3::Application.routes.draw do
  resources :games

  get "static_pages/home"
  root to: 'static_pages#home'
  
  resources :reviews, only: [:create, :destroy]
  resources :critics
  resources :sessions, only: [:new, :create, :destory]

  match '/signup', to: 'critics#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/critic.rb
class Critic < ActiveRecord::Base
  # attr_accessor :email, :name
  attr_accessible :email, :name, :password, :password_confirmation, :remember_token
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL}, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def Critic.new_remember_token
  	SecureRandom.urlsafe_base64
  end

  def Critic.encrypt(token)
  	Digest::SHA1.hexdigest(token.to_s)
  end

  private

  	def create_remember_token
  		self.remember_token = Critic.encrypt(Critic.new_remember_token)
  	end
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :console, :description, :esrb, :image_location, :players, :title
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :critic
  attr_accessible :content, :score, :critic_id
  default_scope -> { order('created_at DESC')}
  validates :critic_id, presence: true
  validates :content, presence: true,  length: { maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/critics_controller.rb
class CriticsController < ApplicationController
  # GET /critics
  # GET /critics.json
  def index
    @critics = Critic.all
  end

  # GET /critics/1
  # GET /critics/1.json
  def show
    @critic = Critic.find(params[:id])
    @reviews = @critic.reviews
  end

  # GET /critics/new
  # GET /critics/new.json
  def new
    @critic = Critic.new
  end

  # GET /critics/1/edit
  def edit
    @critic = Critic.find(params[:id])
  end

  # POST /critics
  # POST /critics.json
  def create
    @critic = Critic.new(params[:critic])
    if @critic.save
      sign_in @critic
      redirect_to @critic
    else
      render 'new'
    end
  end

  # PUT /critics/1
  # PUT /critics/1.json
  def update
    @critic = Critic.find(params[:id])
    if @critic.update_attributes(params[:critic])
      redirect_to @critic
    else
      render 'edit'
    end
  end

  # DELETE /critics/1
  # DELETE /critics/1.json
  def destroy
    @critic = Critic.find(params[:id])
    @critic.destroy
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    @game.save
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_critic.reviews.build(params[:review])
    if @review.save
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

    def review_params
      params.require(:review).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@critic = Critic.find_by_email(params[:session][:email].downcase)
		if @critic && @critic.authenticate(params[:session][:password])
			sign_in @critic
			redirect_to @critic
		else
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@review = current_critic.reviews.build if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/critics_helper.rb
module CriticsHelper
	def avatar_for(critic)
		gravatar_id = Digest::MD5::hexdigest(critic.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: critic.name, class: "gravatar")
	end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(critic)
		remember_token = Critic.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		critic.update_attributes(:remember_token => Critic.encrypt(remember_token))
		self.current_critic = critic
	end

	def signed_in?
		!current_critic.nil?
	end

	def current_critic=(critic)
		@current_critic = critic
	end

	def current_critic
		remember_token = Critic.encrypt(cookies[:remember_token])
		@current_critic ||= Critic.find_by_remember_token(remember_token)
	end

	def sign_out
		self.current_critic = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/critics/_form.html.erb
<%= form_for(@critic) do |f| %>
  <% if @critic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@critic.errors.count, "error") %> prohibited this critic from being saved:</h2>

      <ul>
      <% @critic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/critics/edit.html.haml
- provide(:title, "Edit Profile")
%h1 Update Your Profile
.row
	.span6.offset3
		= for_form (@critic) do |f|
			= render 'shared/error_messages', object: f.object
			= f.label :name
			= f.text_field :name
			= f.label :email
			= f.text_field :email
			= f.label :password
			= f.password_field :password
			= f.label :password_confirmation, "Confirm Password"
			= f.password_field :password_confirmation
			= f.submit "Save Changes", class: "btn btn-large btn-primary"
		= avatar_for @critic
		%a{href: "http://gravatar.com/emails"} change

app/views/critics/index.html.haml
- provide(:title, 'All Critics')
%h1 All Critics
%ul.critics
  - @critics.each do |critic|
    %li
      = avatar_for critic
      = link_to critic.name, critic

app/views/critics/new.html.haml
- provide(:title, 'Sign up')
%h1 Sign Up
.row
	.span6.offset3
		= form_for(@critic) do |f|
			= render 'shared/error_messages', object: f.object
			= f.label :name
			= f.text_field :name
			= f.label :email
			= f.text_field :email
			= f.label :password
			= f.password_field :password
			= f.label :password_confirmation, "Confirmation"
			= f.password_field :password_confirmation
			= f.submit "Become a Critic" , class: "btn btn-large btn-primary"

app/views/critics/show.html.haml
- provide(:title, @critic.name)
.row
	%aside.span4
		%section
			%h1
				= avatar_for @critic
				= @critic.name
	.span8
		- if @critic.reviews.any?
			%h3
				Reviews (#{@critic.reviews.count})
			%ol.reviews
				= render @reviews
      		

app/views/games/_game_form.html.haml
-unless @game.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      -@game.errors.full_messages.each do |error|
        %li= error

= label :game, :title, 'Title'
= text_field :game, :title
%p
= label :game, :esrb, 'ESRB Rating'
= text_field :game, :esrb
%p

= label :game, :console, 'Console'
= text_field :game, :console
%p
= label :game, :players, 'Players'
= text_field :game, :players
%p
= label :game, :description, 'Description'
= text_field :game, :description

app/views/games/edit.html.haml
%h2 Edit Game

= form_tag game_path(@game), :method => :put do
	= render :partial => 'game_form'

	= submit_tag 'Update Info'

app/views/games/index.html.haml
- provide(:title, 'All Games')
%h1 All Games
%ul.critics
  - @games.each do |game|
    %li
      = image_tag game.image_location, :height => "30%", :width => "30%"
      = link_to game.title, game

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.haml
%h1 #{@game.title}

%ul#details
  =image_tag(@game.image_location)
  %li
    ESRB Rating:
    = @game.esrb
  %li
    Console:
    = @game.console
  %li
    Players:
    = @game.players

%h3 Description:

%p#desciption= @game.description

= link_to 'Edit Info', edit_game_path(@game)

= button_to 'Delete', game_path(@game), :method => :delete, :confirm => 'Are you sure?'

= link_to 'Back to Games', games_path

app/views/layouts/application.html.haml
%html
	%head
		%title UReview
		= stylesheet_link_tag 'application'
		= javascript_include_tag 'application'
		= csrf_meta_tags


	%body
		%header.navbar.navbar-fixed-top.navbar-inverse
			.navbar-inner
				.container
					= link_to "UReview", root_path, id: "logo"
					%nav
						%ul.nav.pull-right
							%li= link_to "Home", root_path
							- if signed_in?
								%li= link_to "Critics", critics_path
								%li#fat-menu.dropdown
									%a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
										Account
										%b.caret
									%ul.dropdown-menu
										%li= link_to "Profile", current_critic
										%li= link_to "Settings", edit_critic_path(current_critic)
										%li.divider
										%li
											= link_to "Sign Out", signout_path, method: "delete"
							- else
								%li= link_to "Sign In", signin_path
		.container
			= yield

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.haml
%li
  %span.content= review.content
  %span.timestamp
    Posted #{time_ago_in_words(review.created_at)} ago.

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Score</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.content %></td>
    <td><%= review.score %></td>
    <td><%= review.user_id %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @review.content %>
</p>

<p>
  <b>Score:</b>
  <%= @review.score %>
</p>

<p>
  <b>User:</b>
  <%= @review.user_id %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
	#error_explanation
		.alert.alert-error
			The form contians #{pluralize(object.errors.count, "error")}.
		%ul
			- object.errors.full_messages.each do |msg|
				%li
					* #{msg}

app/views/shared/_review_form.html.haml
= form_for(@review) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new review..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_user_info.html.haml
= link_to avatar_for(current_critic), current_critic
%h1
  = current_critic.name
%span
  = link_to "view my profile", current_critic
%span
  = pluralize(current_critic.reviews.count, "review")

app/views/static_pages/home.html.haml
- if signed_in?
	.row
		%aside.span4
			%section
				= render 'shared/user_info'
			%section
				= render 'shared/review_form'
- else
	.center.hero-unit
		%h1 UReview
		%h2
			Give your ten cents and let the world
			know what games are worth it.
		= link_to "Sign Up", '/signup', class: 'btn btn-large btn-primary'
		= link_to "Browse Games", '/games', class: 'btn btn-large-primary'